# Generated by Django 5.0.6 on 2024-06-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='home_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comments.comment'),
        ),
    ]
